DATASET="t10003"
DATE="2025_2_18_t10003"
DATA_DIR=data python lerobot/scripts/train.py \
  dataset_repo_id=$DATASET \
  policy=pi0_koch_real \
  env=koch_real \
  hydra.run.dir=outputs/train/pi0_$DATE \
  hydra.job.name=pi0_$DATE\
  device=cuda \
  wandb.enable=true \
  resume=false
