DATASET="t10003"
DATE="2025_1_9_t10003"
DATA_DIR=data python lerobot/scripts/train.py \
  dataset_repo_id=${DATASET} \
  policy=vqbet_koch_real \
  env=koch_real \
  hydra.run.dir=outputs/train/vqbet_$DATE \
  hydra.job.name=vqbet_$DATE \
  device=cuda \
  wandb.enable=true \
  resume=true