_target_: lerobot.common.robot_devices.robots.manipulator.ManipulatorRobot
robot_type: koch
calibration_dir: .cache/calibration/koch

# `max_relative_target` limits the magnitude of the relative positional target vector for safety purposes.
# Set this to a positive scalar to have the same value for all motors, or a list that is the same length as
# the number of motors in your follower arms.
max_relative_target: null

leader_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyUSB0
    motors:
      # name: (index, model)
      shoulder_pan: [1, "xl330-m077"]
      shoulder_lift: [2, "xl330-m077"]
      elbow_flex: [3, "xl330-m077"]
      wrist_flex: [4, "xl330-m077"]
      wrist_roll: [5, "xl330-m077"]
      gripper: [6, "xl330-m077"]

follower_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyUSB1
    motors:
      # name: (index, model)
      shoulder_pan: [1, "xl430-w250"]
      shoulder_lift: [2, "xl430-w250"]
      elbow_flex: [3, "xl330-m288"]
      wrist_flex: [4, "xl330-m288"]
      wrist_roll: [5, "xl330-m288"]
      gripper: [6, "xl330-m288"]

cameras:
  view_front:
    # _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera
    # camera_index: 5
    serial_number: 408122072021
    fps: 30
    width: 640
    height: 480
    use_depth: true
  view_side:
    # _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    _target_: lerobot.common.robot_devices.cameras.intelrealsense.IntelRealSenseCamera
    # camera_index: 6
    serial_number: 408322070928
    fps: 30
    width: 640
    height: 480
    use_depth: true



# ~ Koch specific settings ~
# Sets the leader arm in torque mode with the gripper motor set to this angle. This makes it possible
# to squeeze the gripper and have it spring back to an open position on its own.
gripper_open_degree: 35.156
